import type React from 'react';

import { createIcon } from './icon';
import {
  // Navigation and UI
  Home01,
  Settings01,
  User01,
  Users01,
  Plus,
  PlusCircle,
  X,
  XCircle,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronLeftDouble,
  ChevronRightDouble,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ArrowUpRight,
  LinkExternal01,

  // Text and Editor
  Type01,
  Bold01,
  Italic01,
  Underline01,
  Strikethrough01,
  AlignCenter,
  AlignRight,
  AlignJustify,
  List,
  MessageChatCircle, // Using for quote
  Code01,
  CodeBrowser,
  Heading01,
  Heading02,
  HeadingSquare, // Using for h3-h6
  ParagraphWrap,

  // Media and Files
  File01,
  FileAttachment01, // Using for FileText01
  FilePlus01,
  VideoRecorder, // Using for FileVideo01
  Image01,
  ImagePlus,
  Upload01,
  UploadCloud01,
  Download01,

  // Actions
  Edit01,
  Copy01,
  Trash01,
  SearchLg, // Using for Search01
  FilterFunnel01, // Using for Filter
  Share01,
  Eye,
  EyeOff,

  // Communication
  Mail01,
  MessageCircle01,
  MessageSquare01,

  // Time and Calendar
  Clock,
  Calendar,

  // Alerts and Status
  AlertCircle,
  InfoCircle, // Using InfoCircle instead of Info01
  HelpCircle,

  // Shapes and Layout
  Square,
  Circle,

  // Navigation arrows
  DotsHorizontal,
  DotsVertical,
  ChevronSelectorHorizontal,
  ChevronSelectorVertical,

  // Misc
  Globe01,
  Key01,
  Lock01,
  CreditCard01,
  Tag01,
  Star01,
  Heart,
  Palette,
  Brush01, // Using Brush01
  Zap,
  Target03, // Using Target03
  TrendUp01, // Using TrendUp01
  MusicNote01, // Using MusicNote01
  Columns01, // Using Columns01
  Table,
  Move,
  Minus,
  Sun,
  Moon01, // Using Moon01
  LogOut01,

  // Special
  Lightbulb01,
  Phone01,
  Send01,
  Globe06,
  Link01,
  AnnotationDots,
  AlignLeft,
  ImageIndentLeft,
  Image04,
  BezierCurve02,
  Target05,
  Copy05,
  Trash03,
  Link03,
  Link04,
  LayoutLeft,
  Cursor02,
  Columns03,
  Expand03,
  FilterLines,
  CornerDownRight,
  CursorClick02,
  Mail04,
  Copy02,
  PencilLine,
  FileCheck02,
  FileX01,
  UserPlus02,
  Star06,
  DotsGrid,
  ArrowSquareUpRight,
  Share04,
  Annotation,
  ChartBreakoutSquare,
  MagicWand01,
  RefreshCcw02,
  RefreshCcw03,
  BarChart12,
  Youtube,
  UserX01,
  Building06,
  File06,
  Settings04,
  Rows01,
  Rows03,
  SwitchVertical01,
  FileX03,
  Rocket02,
  File02,
  Code02,
  UserEdit,
  Share03
} from '@untitledui/icons';

import { FacebookLogoIcon, GithubLogoIcon, InstagramLogoIcon, LinkedinLogoIcon, TwitterLogoIcon, YoutubeLogoIcon, DotsSixVerticalIcon, SpinnerIcon, Sparkle, GoogleLogoIcon } from '@phosphor-icons/react';

const iconMap = {
  // Navigation icons
  home: Home01,
  dotsSixVerticalIcon: DotsSixVerticalIcon,
  posts: FileAttachment01,
  forms: FilePlus01,

  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowLeftRight: DotsHorizontal,
  arrowRight: ArrowRight,
  link04: Link04,
  cursor02: Cursor02,
  arrowUp: ArrowUp,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsLeft: ChevronLeftDouble,
  chevronsLeftRight: ChevronSelectorHorizontal,
  chevronsRight: ChevronRightDouble,
  chevronsUpDown: ChevronSelectorVertical,
  chevronUp: ChevronUp,
  externalLink: LinkExternal01,
  ellipsis: DotsHorizontal,

  // Editor actions
  add: Plus,
  ai: Star01,
  clear: X,
  close: X,
  combine: Square, // No direct equivalent, using Square
  continueWrite: Edit01,
  copy: Copy01,
  copy02: Copy02,
  copyLink: Copy01,
  delete: Trash01,
  done: Check,
  download: Download01,
  dragHandle: Move,
  edit: Edit01,
  editing: Edit01,
  gripVertical: Move,
  hide: X,
  improve: Zap,
  makeLonger: Plus,
  makeShorter: Minus,
  column03: Columns03,
  minus: Minus,
  plus: Plus,
  plusCircle: PlusCircle,
  refresh: ChevronSelectorHorizontal,
  reset: Clock,
  search: SearchLg,
  sendMessage: ArrowUpRight,
  share: Share01,
  simplify: FilterFunnel01,
  stop: Circle,
  submit: ArrowUp,
  summarize: Zap,
  trash: Trash01,
  tryAgain: ArrowLeft,
  turnInto: ChevronSelectorHorizontal,
  undo: ArrowLeft,
  ungroup: Square,
  x: X,
  zoomIn: Plus,
  zoomOut: Minus,

  // Text formatting
  alignCenter: AlignCenter,
  alignJustify: AlignJustify,
  alignLeft: AlignLeft,
  alignRight: AlignRight,
  blockquote: MessageChatCircle,
  bold: Bold01,
  code: Code01,
  code02: Code02,
  codeblock: CodeBrowser,
  h1: Heading01,
  h2: Heading02,
  h3: HeadingSquare,
  h4: HeadingSquare,
  h5: HeadingSquare,
  h6: HeadingSquare,
  building06: Building06,
  indent: Type01,
  italic: Italic01,
  lineHeight: Type01,
  link: Link01,
  link3: Link03,
  ol: List,
  outdent: Type01,
  paragraph: ParagraphWrap,
  strikethrough: Strikethrough01,
  subscript: Type01,
  superscript: Type01,
  text: Type01,
  ul: List,
  underline: Underline01,
  unlink: X,

  // UI elements
  alertCircle: AlertCircle,
  calendar: Calendar,
  callout: Lightbulb01,
  caption: AnnotationDots,
  annotation: Annotation,
  check: Check,
  checked: Check,
  checkCircle: CheckCircle,
  circle: Circle,
  clock: Clock,
  creditCard: CreditCard01,
  empty: XCircle,
  enter: ArrowRight,
  hidden: EyeOff,
  info: InfoCircle,
  helpCircle: HelpCircle,
  password: Lock01,
  kbd: Key01,
  menu: DotsHorizontal,
  message: MessageCircle01,
  messages: MessageCircle01,
  moon: Moon01,
  more: DotsHorizontal,
  moreX: DotsHorizontal,
  moreY: DotsVertical,
  settings: Settings01,
  sidebar: LayoutLeft,
  slidersHorizontal: FilterFunnel01,
  smile: Heart,
  spinner: SpinnerIcon,
  square: Square,
  sun: Sun,
  todo: Square,
  user: User01,
  userPlus: UserPlus02,
  userRemove: UserX01,
  viewing: Eye,
  warning: AlertCircle,
  key: Key01,
  button: Square,

  // Media and content
  audioUpload: Plus,
  bg: Brush01,
  color: Palette,
  column: Square,
  columns3: Columns01,
  comment: MessageCircle01,
  commentAdd: MessageCircle01,
  document: FileAttachment01,
  dropzone: Upload01,
  editor: FileAttachment01,
  emoji: Heart,
  equation: Type01,
  explain: HelpCircle,
  file: File01,
  post: File02,
  email: Mail01,
  fileUpload: Upload01,
  globe: Globe01,
  internet: Globe06,
  history: Clock,
  image: Image01,
  imageUpload: ImagePlus,
  inlineEquation: Type01,
  insertBelow: Plus,
  mediaFile: File01,
  newPage: FilePlus01,
  original: ArrowUpRight,
  paintbrush: Brush01,
  row: DotsHorizontal,
  sigma: Type01,
  table: Table,
  templates: Square,
  translate: Globe01,
  upload: Upload01,
  uploadCloud: UploadCloud01,
  videoUpload: VideoRecorder,
  video: VideoRecorder,
  tiktok: VideoRecorder, // No TikTok icon, using VideoRecorder
  instagram: InstagramLogoIcon,
  facebook: FacebookLogoIcon,
  twitter: TwitterLogoIcon,
  youtube: YoutubeLogoIcon,
  google: GoogleLogoIcon,
  star: Star01,
  linkedin: LinkedinLogoIcon,
  github: GithubLogoIcon,
  stack: Square,
  palette: Palette,
  logout: LogOut01,

  loaderCircle: SpinnerIcon,
  loader2: SpinnerIcon,
  trash2: Trash03,
  users: Users01,
  settings2: Settings01,
  xCircle: XCircle,
  columns: Columns01,
  tag: Tag01,
  moreHorizontal: DotsHorizontal,
  pencil: Edit01,
  filter: FilterLines,
  trendingUp: TrendUp01,
  eyeOff: EyeOff,
  smartphone: Phone01,
  send: Send01,
  mail: Mail01,
  link2: LinkExternal01,
  link2Off: X,
  focus: Target03,
  audioLines: MusicNote01,
  fileUp: Upload01,
  film: VideoRecorder,
  calendarIcon: Calendar,
  messageSquareText: MessageSquare01,
  checkIcon: Check,
  pencilLineIcon: Edit01,
  xIcon: X,
  fileTextIcon: FileAttachment01,
  linkIcon: LinkExternal01,
  trash2Icon: Trash01,
  squareIcon: Square,
  cornerDownLeft: ArrowDown,
  radical: Type01,
  arrowUpRight: ArrowUpRight,
  plusIcon: Plus,
  fileUpIcon: Upload01,
  filesIcon: File01,
  imageIcon: Image01,
  arrowSquareUpRight: ArrowSquareUpRight,
  share04: Share04,
  ellipsisIcon: DotsHorizontal,
  deleteIcon: Trash01,
  searchIcon: SearchLg,
  houseIcon: Home01,
  arrowUpRightIcon: ArrowUpRight,
  textIcon: Type01,
  sparkles: Sparkle,
  heart: Heart,
  ImageIndentLeft: ImageIndentLeft,
  image4: Image04,
  loader: SpinnerIcon,
  loaderIcon: SpinnerIcon,
  arrowDownToLine: ArrowDown,
  arrowUpToLine: ArrowUp,
  checkSquare: CheckCircle,
  dotsThreeVertical: DotsVertical,
  languages: Globe01,
  audio: MusicNote01,
  compass: Target03,
  bezierCurve02: BezierCurve02,
  target05: Target05,
  dublicate: Copy05,
  lightbulb: Lightbulb01,
  leaf: Heart,
  eye: Eye,
  apple: Circle,
  expand: Expand03,
  longArrowRight: CornerDownRight,
  cursorClick02: CursorClick02,
  time: Clock,
  mail04: Mail04,
  pencilLine: PencilLine,
  fileCheck02: FileCheck02,
  fileX01: FileX01,
  star06: Star06,
  dotGrid: DotsGrid,
  arrowupdo: ArrowUp,
  magicWand: MagicWand01,
  chartCheckoutSquare: ChartBreakoutSquare,
  chevronSelectorHorizontal: ChevronSelectorHorizontal,
  chevronSelectorVertical: ChevronSelectorVertical,
  refreshCcw02: RefreshCcw02,
  refreshCcw03: RefreshCcw03,
  barChart: BarChart12,
  youtubeLogo: Youtube,
  setting04: Settings04,
  rows01: Rows01,
  rows03: Rows03,
  fileX03: FileX03,
  rocket02: Rocket02,
  switchVertical: SwitchVertical01,
  usersEdit:UserEdit,
  key01: Key01,
  share03:Share03
} satisfies Record<string, React.FC<any>>;

export const Icons = Object.fromEntries(
  Object.entries(iconMap).map(([key, IconComponent]) => [
    key,
    createIcon(IconComponent),
  ])
) as Record<IconName, ReturnType<typeof createIcon>>;

export type IconName = keyof typeof iconMap;
